describe('Generate a Report', function (){
    it('Report', function (){
  cy.visit('https://beta01.medireport.dev/')
    cy.get('[placeholder=Username]').type('Support')
    cy.get('[placeholder=Password]').type('Medireport@2019')
    cy.get('[onclick="submitLogin()"]').click( {force: true})
    cy.contains('Cardio').click()
    cy.wait(15000)
    cy.get('.c-qb-dropdown > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
    cy.contains('All patients').click()
    cy.get('#mat-chip-list-input-0').type('JR {Enter}') 
    cy.wait(2000)
    cy.contains('JR').dblclick()
    cy.wait(6000)
    cy.get('.d-flex > .mat-focus-indicator').click()
    cy.wait(2000)
    cy.get('#mat-select-value-7 > .mat-select-placeholder').click()
    cy.get('#mat-option-17').click()
    cy.get('#mat-select-value-9 > .mat-select-placeholder').click()
    cy.get('#mat-input-12').type('autu')
    cy.get('#mat-input-12').clear()
    cy.get('#mat-input-12').type('autu {Enter} ')
    cy.get('#mat-input-12').clear()
    cy.get('#mat-input-12').type('autu')

    })
})