const random = '1' + Math.random().toString()

describe('Pacemaker', function (){
    it('MyPacemaker', function (){
  cy.visit('https://beta01.medireport.dev/')
    cy.get('[placeholder=Username]').type('Support')
    cy.get('[placeholder=Password]').type('Medireport@2019')
    cy.get('[onclick="submitLogin()"]').click( {force: true})
    cy.contains('Cardio').click()
    cy.wait(15000)
    cy.get('.c-qb-dropdown > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
    cy.contains('All patients').click()
    cy.get('#mat-chip-list-input-0').type('JR {Enter}') 
    cy.wait(2000)
    cy.contains('JR').dblclick()
    cy.wait(6000)
    cy.get('.d-flex > .mat-focus-indicator').click()
    cy.wait(2000)
    cy.get('#mat-select-value-7 > .mat-select-placeholder').click()
    cy.get('#mat-option-17').click()
    cy.get('#mat-select-value-9 > .mat-select-placeholder').click()
    cy.get('#mat-input-12').type('autu')
    cy.get('#mat-input-12').clear()
    cy.get('#mat-input-12').type('autu {Enter} ')
    cy.get('#mat-input-12').clear()
    cy.get('#mat-input-12').type('autu')
    cy.wait(3000)
    cy.get('.mat-option-text').click()
    cy.wait(1000)
    cy.get('#saveBtn').click()
    cy.wait(6000)

    /// Material Page
    cy.get('#procedureMaterialSidebar > .d-flex').click()
    cy.wait(3000)
    cy.get('#pickFromCatalogBtn').click()
    cy.wait(2000)
    /// Select a Pacemaker
    cy.get('#mat-chip-list-input-1').type('pacemaker {Enter}')
    cy.wait(2000)
    cy.get('[aria-label="pacemaker1 column header Reference"]').dblclick()
    cy.get('#mat-input-19').type(random)
    cy.get('#saveBtn').click()
    cy.get('#okConfirmBtn').click()
    /// Select a Lead
    cy.get('#pickFromCatalogBtn').click()
    cy.wait(2000)
    cy.get('#mat-chip-list-input-2').type('lead {Enter}')
    cy.wait(2000)
    cy.get('[aria-label="Lead2 column header Reference"]').dblclick()
    cy.get('#mat-input-24').type(random)
    cy.get('#saveBtn').click()
    cy.get('#okConfirmBtn').click()
    cy.wait(2000)
    /// Select a second lead
    cy.get('#pickFromCatalogBtn').click()
    cy.wait(2000)
    cy.get('#mat-chip-list-input-3').type('lead {Enter}')
    cy.wait(2000)
    cy.get('[aria-label="Lead1 column header Reference"]').dblclick()
    cy.get('#mat-input-29').type(random)
    cy.get('#saveBtn').click()
    cy.get('#okConfirmBtn').click()
    cy.wait(2000)
    cy.get('#dashboardSidebar > .d-flex').click()
    cy.wait(2500)
    cy.get('#sectionWrapper > :nth-child(2)').click()
    cy.wait(3000)
    /// Click on button "plus" of pacemaker
    cy.get('body').click(1100, 400)
    cy.wait(2000)
    cy.get('#mat-select-value-43 > .mat-select-placeholder').dblclick()
    cy.get('#mat-select-value-29 > .mat-select-placeholder').click()
    cy.wait(1500)
    cy.get('#mat-input-34').type('r Sub {Enter} ')
    cy.get('#mat-radio-11 > .mat-radio-label > .mat-radio-label-content').click()
    cy.get('.sections-wrapper').scrollTo(0, 500)
    /// Click on button "plus" of lead
    cy.get('body').click(1200, 300)
    })

})